const ENTRAR = {
    SOLICITUD:"ENTRAR_SOLICITUD",
    CORRECTO:"ENTRAR_CORRECTO",
    FALLIDO: "ENTRAR_FALLIDO",
    LIMPIAR_ERROR:"ENTRAR_LIMPIAR_ERROR"
    
}
const SALIDA= {
    SOLICITUD:"ENTRAR_SOLICITUD",
    CORRECTO:"ENTRAR_CORRECTO",
    FALLIDO: "ENTRAR_FALLIDO",
    
}


export { ENTRAR, SALIDA };
